### ISSUE TITLE
More granular star fill (average)

### ISSUE THREAD

**Issue by piszczu4** [smastrom/react-rating#18]
Is there a chance to add a possibility to fill star in 2/3 instead of filing it either entirely or in half? I need for "average" rating displaying

**Comment by smastrom** [comment]
Hi @piszczu4, this library handles fraction fills at maximum 1/2, using rounding when opportune. That's by design and will unlikely ever change.

In this case, I would suggest to use [Mantine Rating](https://mantine.dev/core/rating/#fractions) instead which gives you total control over fractions.

**Comment by mlahargou** [comment]
We were looking for a replacement for https://github.com/ekeric13/react-star-ratings as that project seems to be abandoned. This is a key feature we would need.
