### ISSUE TITLE
Styles are not imported

### ISSUE THREAD

**Issue by piszczu4** [smastrom/react-rating#19]
I did

```
import { Rating } from '@smastrom/react-rating';

   <Rating
        value={4}
        items={6}
        style={{ maxWidth: 100 }}
        // className='flex w-[200px]'
      />
```

but when looking at devtools, the styles are not imported. Here is the output:

![image](https://github.com/smastrom/react-rating/assets/88668060/4a7c250b-004b-44d9-a00d-689d41413ffa)

What am I doing wrong?

**Comment by YoFiq** [comment]
import '@smastrom/react-rating/style.css';
 and will work
