### ISSUE TITLE
Setting default rating value causes first onChange value always be 0

### ISSUE THREAD

**Issue by andrewshvv** [smastrom/react-rating#20]
Hey, the example from docs, but with default value of rating being non 0, causes first value of onChange handler be 0 ignoring the user input. Following updates of rating are correctly handled and corresponding user inputs are received in onChange handler.

**Comment by smastrom** [comment]
Hi @andrewshvv, while I trust that something is not working as expected, your issue is not clear enough and I can't look at it unless you provide some kind of reproduction of the expected behavior.

**Comment by andrewshvv** [comment]
@smastrom sure, here it is, click on 3rd star, it will show 0
https://playcode.io/1895956

**Comment by smastrom** [comment]
Hi @andrewshvv, this is expected. By default the rating can be reset (set to 0) when clicking on the current correspondent rating star using the mouse or the keyboard. 

This behavior can be disabled by setting `isRequired` prop to `true`:

https://reactrating.netlify.app/#required

**Comment by smastrom** [comment]
Hi @andrewshvv, this is expected. By default the rating can be reset (set to 0) when clicking on the current correspondent rating star using the mouse or the keyboard. 

This behavior can be disabled by setting `isRequired` prop to `true`: https://reactrating.netlify.app/#required

**Comment by andrewshvv** [comment]
@smastrom thank u very much!
