### ISSUE TITLE
Umd format may not be working properly

### ISSUE THREAD

**Issue by frainho** [smastrom/react-rating#3]
Hello, I was looking for a great ratings package for a project and stumbled upon yours!

It looks great and it has great documentation so congratulations for that! 🎉 👏 

I tried to install it in a project I'm working on and it's not working as expected. It seems `package.json` is looking for a `index.umd.min.js` but vite is building a `index.umd.js`.

package.json - https://github.com/smastrom/react-rating/blob/main/package.json#L38
vite.config.js - https://github.com/smastrom/react-rating/blob/main/vite.config.ts#L33

When I import it in my project I get:
`Cannot find module '/Users/.../Code/projects/../node_modules/@smastrom/react-rating/dist/index.umd.min.js'`.

I tried to do a code sandbox with a repro but I didn't get it to spit out the error. Let me know if you want me to do a reproduction repo

**Comment by smastrom** [comment]
Hi Felipe,

Thank you **very much** for raising this issue. Yes, package.json was pointing to a wrong filename for UMD version.

I just published `1.0.3` that solves this issue and ables you to import the css without the .css extension:

`import '@smastrom/react-rating/style';`

I tried to `const { Rating } = require('@smastrom/react-rating');` in a .cjs file and no errors so far.

I have one question though, in which context where you importing the UMD module that you needed it instead that ESM?

Thank you again.

**Comment by frainho** [comment]
Wow, so fast! Thank you for this. Will test it!

I'm using this in a Remix project and it tried to use the UMD version by default.

I need to take a deeper look and see if I can get it running with ESM.

**Comment by smastrom** [comment]
Thank you for your feedback Felipe. I never tested it with RemixJS, I did it with NextJS instead.

You can take a look here on how to import ESM within Remix:
[https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages)

And please, let me know if everything works by using the UMD version. Thanks again.

**Comment by smastrom** [comment]
I had it working within a web container. You just have to import the CSS as I did here:

[https://stackblitz.com/edit/node-rvoenm?file=app/routes/index.tsx](https://stackblitz.com/edit/node-rvoenm?file=app/routes/index.tsx)

***routes/index.tsx***
```tsx
import React, { useState } from 'react';
import { Rating } from '@smastrom/react-rating';

import styles from '@smastrom/react-rating/style.css';

export function links() {
  return [{ rel: 'stylesheet', href: styles }];
}

export default function Index() {
  const [ratingValue, setRatingValue] = useState(3);
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', lineHeight: '1.4' }}>
      <h1>Welcome to Remix</h1>
      <Rating
        style={{ maxWidth: 250 }}
        value={ratingValue}
        onChange={(selectedValue) => setRatingValue(selectedValue)}
      />
    </div>
  );
}
```

**Comment by smastrom** [comment]
I never tested with Remix but did it with NextJS instead.

In any case I had it working within a web container. You can use ES6 import and setup the CSS as I did here:

[https://stackblitz.com/edit/node-rvoenm?file=app/routes/index.tsx](https://stackblitz.com/edit/node-rvoenm?file=app/routes/index.tsx)

***routes/index.tsx***
```tsx
import React, { useState } from 'react';
import { Rating } from '@smastrom/react-rating';

import styles from '@smastrom/react-rating/style.css';

export function links() {
  return [{ rel: 'stylesheet', href: styles }];
}

export default function Index() {
  const [ratingValue, setRatingValue] = useState(3);
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', lineHeight: '1.4' }}>
      <h1>Welcome to Remix</h1>
      <Rating
        style={{ maxWidth: 250 }}
        value={ratingValue}
        onChange={(selectedValue) => setRatingValue(selectedValue)}
      />
    </div>
  );
}
```

I will update the documentation on how to import styles with Remix. Thank you again for the report.
